apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: counter-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
      - name: counter-backend
        image: counter-backend:latest
        imagePullPolicy: Never  # Koristi lokalni image
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: counter-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP