name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Image Tag
      id: tags
      run: |
        SHORT_SHA=$(git rev-parse --short=7 HEAD)
        echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "Building: ${SHORT_SHA}"
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Backend Image
      run: |
        IMAGE=zoddo16/counter-backend
        TAG=${{ steps.tags.outputs.sha }}
        
        docker build -t ${IMAGE}:${TAG} .
        docker push ${IMAGE}:${TAG}
        
        docker tag ${IMAGE}:${TAG} ${IMAGE}:main
        docker push ${IMAGE}:main
    
    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4
      with:
        repository: srdjanbozic/CounterApp_Infra
        path: infra
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: terraform -chdir=infra init
    
    - name: Terraform Apply
      run: |
        terraform -chdir=infra apply -auto-approve \
          -var="frontend_image=zoddo16/counterapp-ui:main" \
          -var="backend_image=zoddo16/counter-backend:${{ steps.tags.outputs.sha }}"
    
    - name: Verify Deployment
      run: |
        kubectl get pods -n counterapp
        kubectl rollout status deployment/backend-deployment -n counterapp --timeout=300s
