name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: counter-backend
  DEPLOYMENT_NAME: backend-deployment
  CONTAINER_NAME: counter-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Running tests..."
        # python -m pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/counter-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/counter-backend:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Minikube
      run: |
        kubectl --kubeconfig=/home/zodd/.kube/config get nodes
        kubectl --kubeconfig=/home/zodd/.kube/config set image deployment/backend-deployment counter-backend=${{ secrets.DOCKER_USERNAME }}/counter-backend:latest
        kubectl --kubeconfig=/home/zodd/.kube/config rollout status deployment/backend-deployment
        echo "🎉 Deploy completed!"
